name: iOS Emulator Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ios-tests:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Install WDIO + Appium
      run: |
        npm install @wdio/cli @wdio/local-runner @wdio/mocha-framework @wdio/appium-service
        npm install appium

    - name: Install Appium Drivers
      run: npx appium driver install xcuitest

    - name: Show Xcode & Simulators
      run: |
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        xcodebuild -version
        xcrun simctl list

    - name: Boot iOS Simulator
      run: |
        xcrun simctl shutdown all || true
        xcrun simctl boot "iPhone 15"
        xcrun simctl bootstatus "iPhone 15"

        # IMPORTANT: No manual "Start Appium Server" step here
        # We rely on WDIO's built-in service

    - name: Run WebdriverIO Tests
      run: npx wdio run wdio.conf.js --logLevel debug
    
    
    - name: Install Allure via Homebrew
      run: |
        brew tap qameta/allure
        brew install allure

    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure HTML
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report

    - name: Archive Artifacts and Upload
      if: always()
      run: |
       mkdir -p artifacts
       # Copy appium.log if it exists
       [ -f ./appium.log ] && cp ./appium.log ./artifacts || echo "No Appium log found."
       # Copy the screenshots folder if it exists
       [ -d ./screenshots ] && cp -r ./screenshots ./artifacts || echo "No screenshots directory found."
       # Create a zip
       zip -r artifacts.zip artifacts

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
       name: test-artifacts
       path: artifacts.zip

